version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/sudoku_app
      - FRONTEND_URL=http://localhost:5173
      - CORS_ORIGIN=http://localhost:5173
      - JWT_SECRET=dev_secret_change_me
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
